/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./shadcn-vue/components/alert/Alert.vue')['default']
    AlertDescription: typeof import('./shadcn-vue/components/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./shadcn-vue/components/alert/AlertTitle.vue')['default']
    Auth: typeof import('./sections/Auth.vue')['default']
    Board: typeof import('./sections/Board.vue')['default']
    BoardHeader: typeof import('./components/BoardHeader.vue')['default']
    BoardLayout: typeof import('./components/BoardLayout.vue')['default']
    BoardSection: typeof import('./components/BoardSection.vue')['default']
    BoardShift: typeof import('./components/BoardShift.vue')['default']
    BoardView: typeof import('./sections/BoardView.vue')['default']
    BoardZone: typeof import('./components/BoardZone.vue')['default']
    Button: typeof import('./shadcn-vue/components/button/Button.vue')['default']
    Card: typeof import('./shadcn-vue/components/card/Card.vue')['default']
    CardContent: typeof import('./shadcn-vue/components/card/CardContent.vue')['default']
    CardDescription: typeof import('./shadcn-vue/components/card/CardDescription.vue')['default']
    CardFooter: typeof import('./shadcn-vue/components/card/CardFooter.vue')['default']
    CardHeader: typeof import('./shadcn-vue/components/card/CardHeader.vue')['default']
    CardTitle: typeof import('./shadcn-vue/components/card/CardTitle.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Input: typeof import('./shadcn-vue/components/input/Input.vue')['default']
    Label: typeof import('./shadcn-vue/components/label/Label.vue')['default']
    Login: typeof import('./sections/Login.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Nav: typeof import('./sections/Nav.vue')['default']
    Popover: typeof import('./shadcn-vue/components/popover/Popover.vue')['default']
    PopoverAddProvider: typeof import('./components/PopoverAddProvider.vue')['default']
    PopoverContent: typeof import('./shadcn-vue/components/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./shadcn-vue/components/popover/PopoverTrigger.vue')['default']
    Select: typeof import('./shadcn-vue/components/select/Select.vue')['default']
    SelectContent: typeof import('./shadcn-vue/components/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./shadcn-vue/components/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./shadcn-vue/components/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./shadcn-vue/components/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./shadcn-vue/components/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./shadcn-vue/components/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./shadcn-vue/components/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./shadcn-vue/components/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./shadcn-vue/components/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./shadcn-vue/components/select/SelectValue.vue')['default']
    ShiftList: typeof import('./components/ShiftList.vue')['default']
  }
}
